name: Node.js CI Reusable Workflow

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        description: 'Node.js version to use'
        required: false
        default: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Use Node.js ${{ inputs['node-version'] }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs['node-version'] }}
    - name: Run ci
      run: npm ci
    - name: Run build
      run: npm run build --if-present
    - name: Run test
      run: npm test